import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from 'sonner';
import NextTopLoader from 'nextjs-toploader';
import ThemeNext from '@/components/theme-next';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HabitBuilder',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeNext attribute="class" defaultTheme="system" enableSystem>
          <NextTopLoader color="#94a3b8" height={2.5} showSpinner={false} />
          {children}
          <Toaster />
        </ThemeNext>
      </body>
    </html>
  )
}
